---
title: "Acerca de este sitio"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

### Sobre el sitio

*Mixcalco* o el lugar de la casa de las nubes es mi sitio personal en donde busco ensayar ideas a la vez que sirve de repositorio para compartir las cosas que he aprendido o herramientas que encuentre por ahí. 

### Sobre mí

Soy biólogo egresado de la Universidad Nacional Autónoma de México, en donde también cursé mis estudios de maestría. Mis trabajos de investigación han sido variados. Durante el pregrado realicé en un análisis ecológico de las dinámicas poblaciones de un pastizal semiárido. En la maestría investigués sobre las percepciones del clima-tiempo de campesinos indígenas y su vínculo con la dinámicas agrícolas. Actualmente me encuentro estudiando mi doctorado en ciencias ambientales con una especialización en Geografía en la Universidad de la Ciudad de Nueva York (CUNY). Mis intereses académicos van desde la ecología y la etnobiología, hasta la ecología política, la antropología, y la filosofía de la ciencia (aunque no sepa mucho de las últimas dos).

Fuera de la academica disfruto la caminatas tranquilas, disfrutar las tardes viendo las nubes. Me encanta bailar salsa y entrenar Muay Thai.


